Non func
BME-MIT-IET/iet-hf2021-sumatra-csak-jobb pull request #10
Opened 2021-05-09 17:18 UTC by karsazoltan

Nem funkcionális tesztek vizsgálata

2021-05-10 10:41 UTC, attilakillin requested changes
Szerintem korrekt a beszámoló, kitérsz mindenre, jól néznek ki a grafikonok, vannak adatok, stb.

Egy dolog hiányzik: A benchmarkoláshoz a how-to - Milyen gradle taszkokat kell futtatni, hogyan kell elindítani a benchmarkot, ilyenek. Pl. az én gépemen a `jmh` taszk nem fut le, elvben a plugin hibája miatt, de ez nem gond, mert a benchmarkhoz úgysem ezt használjuk, hanem a `jmhJar` taszkot, és utólag futtatjuk ezt a jar fájlt. Ezt viszont beleírhatnád a reportba, hogy aki el akarja végezni a tesztelést, az mit is csináljon.

Illetve a `report.md` fájlt egyszer átfuthatnád, mert kapásból a következő elírásokat találtam:
- 5\. sor: Initializatinon -> Initialization
- 7\. sor: nyilván valóan -> nyilvánvalóan
- 19\. sor: tőbb ->több, mezően -> mezőn
- 24\. sor: pont a mondat végén
- 52\. sor: porgrammal -> programmal
- 56\. sor: szomszédsággi -> szomszédsági, szorását -> szórását

Igazából ezek mellékesek, a fontosabb dolog az útmutató a jmh-hoz.

2021-05-13 11:22 UTC, attilakillin approved these changes
Szuper, így szerintem érthetőbb. Még mindig van egy-két typo (pl. a 24000MHz-es RAM sebesség), de nem vészes. Approved.

2021-05-15 14:51 UTC, karsazoltan commented
A jelzett hibák, elírások javításra kerültek

2021-05-15 15:38 UTC, attilakillin approved these changes
Approved.

2021-05-15 15:40 UTC, merged