Unit testing
BME-MIT-IET/iet-hf2021-sumatra-csak-jobb pull request #12
Opened 2021-05-12 23:57 UTC by szinuccsi

Unit tesztelés
- Komment módosítások meg lettek téve
- Jelenlegi method coverage 47%, line coverage 30%

2021-05-15 15:20 UTC, karsazoltan requested changes
A mana fogyását az egyes karaktereknél még lehetne vizsgálni.

2021-05-15 15:31 UTC, 4rctopus requested changes
Jók a tesztek és elég is van belőle. Megjelöltem egy sort ami látszólag hiába van ott, valószínűleg csak ki kell törölni és az megoldja a problémát.

2021-05-15 15:31 UTC, 4rctopus commented on src/test/sumatra/TileTest.java
> +        ArrayList<Tile> neighbors = tile.getNeighbors();
Ez a sor hiába van, később nincs felhasználva a neighbors.

2021-05-15 21:24 UTC, szinuccsi commented on src/test/sumatra/TileTest.java
> +        ArrayList<Tile> neighbors = tile.getNeighbors();
Kiszedtem

2021-05-16 00:49 UTC, 4rctopus approved these changes
Megnéztem az újabb teszteket is és jók.

2021-05-16 12:32 UTC, karsazoltan approved these changes

2021-05-16 12:37 UTC, merged